# Generated by Django 4.2.3 on 2023-08-01 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSupported', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='', max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 8, 1, 13, 59, 45, 724193, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
