# Generated by Django 4.2.3 on 2023-08-01 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlatRate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculator',
            name='Salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculator',
            name='Years',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculator',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 14, 9, 21, 862752, tzinfo=datetime.timezone.utc)),
        ),
    ]
