# Generated by Django 4.2.3 on 2023-08-01 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlatRate', '0003_alter_calculator_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='Price',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='Salary',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='Years',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 14, 59, 30, 402561, tzinfo=datetime.timezone.utc)),
        ),
    ]
