# Generated by Django 4.2.3 on 2023-08-01 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlatRate', '0004_alter_calculator_price_alter_calculator_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='Price',
            field=models.PositiveBigIntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='Salary',
            field=models.PositiveBigIntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='Years',
            field=models.PositiveBigIntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 15, 2, 48, 720096, tzinfo=datetime.timezone.utc)),
        ),
    ]
