# Generated by Django 4.2.3 on 2023-08-01 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlatRate', '0006_calculator_downpay_alter_calculator_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='IntrestRate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 15, 26, 4, 215920, tzinfo=datetime.timezone.utc)),
        ),
    ]
