# Generated by Django 4.2.3 on 2023-08-01 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlatRate', '0007_calculator_intrestrate_alter_calculator_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='DownPay',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='IntrestRate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='Price',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='Salary',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='Years',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 21, 31, 45, 890409, tzinfo=datetime.timezone.utc)),
        ),
    ]
